### ISSUE TITLE
[QC][local] multiple validator key - dev/consensus-multi-testnet

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#1059]
- [x] transaction 
- [x] pDex
- [x] Portal BNB
- [x] Stake
- [x] Reward
- [x] Shield/Unshield

**Comment by khanhj** [comment]
Retest on local with new merge from branch beacon fullnode

**Comment by khanhlh-incognito** [comment]
retest with new merge from beacon-fullnode

**Comment by khanhlh-incognito** [comment]
testing done
