### ISSUE TITLE
JSON Capitalisation 

### ISSUE THREAD

**Issue by discoli-zz** [incognitochain/incognito-chain#1060]
Hello, I'm currently using the chain on a Go program I'm developing but noticed that you have not added struct tags to objects with are `json.Marshal`'d

i.e. 

```
type KeyWallet struct {
	Depth       byte   // 1 bytes
	ChildNumber []byte // 4 bytes
	ChainCode   []byte // 32 bytes
	KeySet      incognitokey.KeySet
}
```

should become..

```
type KeyWallet struct {
	Depth       byte                `json:"depth"`        // 1 bytes
	ChildNumber []byte              `json:"childNumber"` // 4 bytes
	ChainCode   []byte              `json:"chainCode"`   // 32 bytes
	KeySet      incognitokey.KeySet `json:"keySet"` 
}
```

The struct tags not being implemented also causes the RPC server to return the data keys serialised in PascalCase as opposed to camelCase or snake_case.

Although there is no official naming conventions for JSON, [Google's (Go) convention](https://google.github.io/styleguide/jsoncstyleguide.xml) recommends using snakeCase.

It'd be a nice QOL change as when using the chain in my personal project there is a mismatch in my capitalisation and Incognito's.

**Comment by discoli** [comment]
On second thought, it's be quite a large change and may break existing programs which have used certain capitalisation.

I'll leave this open for now though since I still think it'd look a lot cleaner & more professional using camelCase or snake_case until an official reply.

**Comment by discoli** [comment]
Also whilst working with the code I noticed a fair few inconsistencies in capitalisation in the RPC interface, some following camelCase and others all lowercase.

![Image](https://i.imgur.com/bTYAbQt.png)

**Comment by khanhlh-incognito** [comment]
Thank you for pointing out this issue. We have no plan to revise them to camelCase as they're not affecting blockchain functionality, and some RPC requests/responses are just being used for debugging purposes.
