### ISSUE TITLE
[QC] transaction performance testscript

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#1081]
- able to config number of tx per second. eg: 30 txs per sec 
- able to config duration of the test. eg: 10 seconds continuously 
- able to config 1shard, xshard tx
- able to config w/wo privacy

**Comment by thach-incognito** [comment]
Done:
https://github.com/incognitochain/incognito-chain-testing/blob/dev/IncognitoChain/TestCases/Performace/test_PER99.py
### How to use:
- Open test scrip and edit LOOP,  TX_PER_LOOP, GAP_BETWEEN_LOOP as you wish
- go to incognito-chain-testing folder and run following command
`run.sh <your test bed> Account8000 IncognitoChain/TestCases/Performace/test_PER99.py`
