### ISSUE TITLE
Staked Pnode and Vnodes earn while offline

### ISSUE THREAD

**Issue by 0xmatt1** [incognitochain/incognito-chain#1166]
This is a known issue and haven't seen it posted officially here on git.... so this is for formality sake.  The talked about remedy was enabling slashing, although it seems the current staking system has a serious design flaw if you can be selected to earn and not actually be online to validate transactions (that is the whole point of running a node is it not?)

**Comment by khanhlh-incognito** [comment]
The node showing offline but still sending "Vote for block" could be an issue with Node monitor to track Node status "online/offline".

The chain keep track of vote state, as you can call request:
```
curl --location --request POST 'https://mainnet.incognito.org/fullnode' --header 'Content-Type: application/json' --data-raw '{
    "id": 1,
    "jsonrpc": "1.0",
    "method": "getbeaconbeststatedetail",
    "params": []
}'
```

check session Vote count "MissingSignature"
```
        "1yGA52wd7RTgP8UbXWnqYPg33cLPdNN4Rp9EgnjPLRmArUZG1C": {
                "ActualTotal": 306,
                "Missing": 2
            },
            "1ywFQqCZNpcPDahY9y8vsHWDK9PuocvtmBmFfuKhGh81MK8HU3": {
                "ActualTotal": 306,
                "Missing": 16
            },
            "1ywRMuTaVWYvquNYurGzE9BkPwxiuUyZQXqgPBTwezhABJxAzJ": {
                "ActualTotal": 306,
                "Missing": 42
            },
            "1zPiEWHDYYzutH5sA6S37K8YUS665QvqbphSAsqTSqTj3C4HWF": {
                "ActualTotal": 306,
                "Missing": 1
```

If a node in committee but missing more than 50% of the actual total block, it will get slashed.
