### ISSUE TITLE
Critical cryptography flaw in decoy addresses

### ISSUE THREAD

**Issue by 0xmatt1** [incognitochain/incognito-chain#1167]
Please see post on forums regarding this critical cryptographic flaw in the core privacy protocol,  citation marked below along with original message:

"The decoy selection seems to be from a uniform distribution. This is a problem because the timestamp of the actual input is usually more recent than all of the randomly selected decoys. I’ve had a look at recent transactions in the explorer and for most the actual input was quite obvious.

Monero had this issue a few years ago and they updated their decoy selection algorithm to select 50% of decoys from the past 1.8 days. See point 8 here: https://www.getmonero.org/2018/03/29/response-to-an-empirical-analysis-of-traceability.html "

Source:

https://we.incognito.org/t/decoy-selection-issue/10953

**Comment by khanhlh-incognito** [comment]
https://we.incognito.org/t/decoy-selection-issue/10953/10
Not an issue as discussed in this topic.
