### ISSUE TITLE
Scripts under incognito-chain/bin/build_*.sh out of date

### ISSUE THREAD

**Issue by uberspot** [incognitochain/incognito-chain#1232]
Hi, :) 

The docker build process changed, and the keylist configs have been moved as well, so the build_* scripts under bin/ are out of date and should be updated/removed (?).

**Comment by 0xankylosaurus** [comment]
Thanks for your report. Those scripts are unused now, we'll remove those in the next release.

**Comment by 0xankylosaurus** [comment]
Merged the update into `production` branch, closing the issue, thanks again for the report.
