### ISSUE TITLE
Cannot load wallet 

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#289]
Followed the instruction from README.md to start a node and got the following error.

![image (9)](https://user-images.githubusercontent.com/4691695/66936131-62b77a00-f067-11e9-97f9-6ba78b2ba9ef.png)

**Comment by thaibao-incognito** [comment]
When using command line to run a node and want to use wallet serverside. Need to --walletautoinit for an initialization fo a not existed wallet
