### ISSUE TITLE
[Fault tolerrant] Transaction stuck in mempool after stop, start block producer

### ISSUE THREAD

**Issue by khanhj** [incognitochain/incognito-chain#291]
- Description: assume that shard0-0 is the node that proposes new block, stopping it also means halt all incoming and outgoing transaction. However, when the node starts working again, all transaction mempool should be processed. 
- Step to reproduce:
1. stopping shard0-0
2. send PRV from shard0-5 to an address in shard4
3. check mempool of shard0-5
4. restart shard0-0

- Expectation: after step4, transaction in mempool is processed, address in shard4 received PRV
- Observation: after step4, any outgoing transaction from shard0-5 will be stacked in its mempool

- Recovery mechanism: restart shard0-5
- Note: the same issue happen when stopping more than 1/3 nodes in one shard.

**Comment by thaibao-incognito** [comment]
I think this is an accepted issue, because node shard0-0 is stopped, so no any other nodes can send message to it and we can not retry and retry again to do that

**Comment by khanhlh-incognito** [comment]
![image](https://user-images.githubusercontent.com/54876297/67173833-3050a880-f3ea-11e9-9cd8-513140c4359e.png)
![image](https://user-images.githubusercontent.com/54876297/67173847-3ba3d400-f3ea-11e9-8561-6426358f41a6.png)

**Comment by khanhlh-incognito** [comment]
verified on TESTNET 20191022
