### ISSUE TITLE
Highway v0: forward messages between Incognito nodes

### ISSUE THREAD

**Issue by 0xbunyip** [incognitochain/incognito-chain#296]
Problems with current design of network topology:
1. Incognito Nodes stay behind NAT => cannot connect directly to each other
2. Random topology => inefficient usage of network bandwidth when broadcasting messages

Propose solution: highways with public IP connect to Nodes and help forwarding messages

Highway v0: single highway supports entire network. ETA: mainnet 16/10/2019

**Comment by khanhlh-incognito** [comment]
Bug #539
