### ISSUE TITLE
[specs] Create the Incognito Architecture document

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#309]

**Comment by duyhtq** [comment]
It's difficult for new team members to read the source code (1M+ lines already!).  We need a simple architecture document to help new team members to get up to speed faster.  It's also helpful for the community to understand and give feedback on our architecture and design.

cc @vvstdung89 @thaibao-incognito

**Comment by duyhtq** [comment]
diagram by @0xkumi from core team meeting on oct 17, 2019
 
![image](https://user-images.githubusercontent.com/4691695/67057616-748a4180-f17b-11e9-857b-3bb6a4b62894.png)

**Comment by duyhtq** [comment]
redesign the architecture diagram.  review needed by the core team.

![incognito architecture](https://user-images.githubusercontent.com/4691695/67062575-ea97a400-f18d-11e9-9a24-c4534cffe3ef.jpg)

**Comment by 0xbunyip** [comment]
Where do the blockchain/privacy packages fit in the new diagram?

**Comment by khanhlh-incognito** [comment]
the big blue stripe is the `pubsub`?

**Comment by duyhtq** [comment]
updated, simplified diagram

![image](https://user-images.githubusercontent.com/4691695/67088588-b9d85e80-f1cf-11e9-855f-d863e09ed774.png)

**Comment by duyhtq** [comment]
try a new format that hopefully explains the building blocks of incognito better.  we'll need another one to explain how these components interact with one another.

![image](https://user-images.githubusercontent.com/4691695/67144203-5a954f80-f29e-11e9-909e-c7e88044575f.png)
