### ISSUE TITLE
[WIP] Testing Tutorial

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#317]
it would be really helpful for new team members and also for the community to understand how to write tests for incognito.  let's create a simple *testing tutorial* document that any developer can pick up and write tests for incognito.  

the tutorial should cover the following.

1.  instruction on how to boot up a *local incognito chain*.  they should be able to config it such as the number of shards, committee size, etc.

2.  a few examples on how to write tests such as how to test sending transactions.

**Comment by khanhlh-incognito** [comment]
working on config to run chain on 1 server

**Comment by khanhlh-incognito** [comment]
https://docs.google.com/document/d/1TrJ-RS2ov7I4CtMocs9gCPeqGodyXbnpWF_bemD8qVU/edit?usp=sharing

**Comment by khanhlh-incognito** [comment]
Task 1: Documentation - DONE
please check this: https://github.com/incognitochain/incognito-chain/blob/dev/master/GettingStarted.md

Task 2: writing sample test script, sending tx (RPC), using golang - INPROGRESS
