### ISSUE TITLE
[specs] Staking

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#334]
as it is closer to mainnet launch, let's review our staking assumptions

1.  what is the number of shards at launch?

2.  what is the number of validators per shard at launch?

3.  what is the number of substitutions?

4.  what is the number of substitutes?

5.  what is the number of candidates?

6.  what is the length of an epoch?

then, review these

7.  what is the staking amount?  is 1750 PRV still a good number after our experience with the testnet -- considering that 95% of PRV is mined through block rewards?

8.  what are the average earnings (block rewards) per day, week, and month from staking point?  or their ROI or % of earning on staking amount.  the higher better.

9.  how long does a validator have to wait to get their earning from staking point?  the earlier the better.

10.  what about bridge validators?

11.  what about beacon validators?

12. What is the min fee?

and let's put into a spec to clearly define these numbers.

**Comment by thaibao-incognito** [comment]
Add more
12. What is the min fee?
