### ISSUE TITLE
Internal audit of Ethereum-Incognito Trustless Bridge

### ISSUE THREAD

**Issue by duyhtq** [incognitochain/incognito-chain#336]
we'll start an external audit with a 3rd party firm soon (to be finalized between peckshield and openzeppelin).  

- [ ] prior to that, let's do an internal audit of our smart contracts on ethereum

- [ ] let's figure out a way if we can separate the bridge logic on our chain so that we can have them review that too

**Comment by 0xankylosaurus** [comment]
Revisiting the issue,  we will be starting working on this next week (Oct 12, 2020)
