### ISSUE TITLE
[Consensus] Fixing N validators of committee of shard in early M blocks

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-chain#339]
N = 22 validators?
M = 10,000,000 blocks?

**Comment by thaibao-incognito** [comment]
We fix 22 validators for early mainnet and update later

**Comment by 0xmerman** [comment]
I have implement this feature and run test for two day. So far so good
This issue related to our bridge as well. So we should wait for the bridge to be well test.
