### ISSUE TITLE
[spec] Privacy-enhancing Overlay for Incognito Network(mask IP address)

### ISSUE THREAD

**Issue by 0xgazeka** [incognitochain/incognito-chain#340]
### Privacy-enhancing Overlay for Incognito Network

_Goal_: Implement I2P anonymous network layer over Incognito network
_Milestone_: mainnet v2

**Comment by duyhtq** [comment]
@0xgazeka please also talk to Binh (the node device team lead) to see if we can integrate i2p for the device too.

**Comment by thaibao-incognito** [comment]
Ref: https://bitcoinmagazine.com/articles/anatomy-anonymity-how-dandelion-could-make-bitcoin-more-private

Ref https://btcmanager.com/what-is-kovri-why-is-it-important-for-monero/?q=/what-is-kovri-why-is-it-important-for-monero/&
