### ISSUE TITLE
[ValidateTransaction] Cannot validate transaction for signing block

### ISSUE THREAD

**Issue by 0xkumi** [incognitochain/incognito-chain#364]
2019-10-24 11:33:20.651 bftactor.go:212 [ERR] Consensus log: -1000: Unexpected error
 -1057: Responsed Transaction With Metadata Error
 Wrong amount 5809152801795 5838033141795
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).ValidateResponseTransactionFromTxsWithMetadata
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/blockchain.go:1458
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).verifyPreProcessingShardBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardprocess.go:474
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).VerifyPreSignShardBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardprocess.go:45
github.com/incognitochain/incognito-chain/blockchain.(*ShardChain).ValidatePreSignBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardchain.go:162
github.com/incognitochain/incognito-chain/consensus/blsbft.BLSBFT.validatePreSignBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/validation.go:73
github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).Start.func1
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/bftactor.go:210
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
Responsed Transaction With Metadata Error
github.com/incognitochain/incognito-chain/blockchain.NewBlockChainError
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/error.go:328
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).verifyPreProcessingShardBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardprocess.go:476
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).VerifyPreSignShardBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardprocess.go:45
github.com/incognitochain/incognito-chain/blockchain.(*ShardChain).ValidatePreSignBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/blockchain/shardchain.go:162
github.com/incognitochain/incognito-chain/consensus/blsbft.BLSBFT.validatePreSignBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/validation.go:73
github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).Start.func1
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/bftactor.go:210
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
Unexpected error
github.com/incognitochain/incognito-chain/consensus.NewConsensusError
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/error.go:56
github.com/incognitochain/incognito-chain/consensus/blsbft.BLSBFT.validatePreSignBlock
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/validation.go:74
github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).Start.func1
        /home/jenkins/workspace/Build_IncognitoTestnet/consensus/blsbft/bftactor.go:210
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by 0xakk0r0kamui** [comment]
Cause of this issue is change data structure of reward instruction but not remove database before re-deploy.
