### ISSUE TITLE
[privacy] implement one-time address

### ISSUE THREAD

**Issue by 0xkraken** [incognitochain/incognito-chain#414]
relative #307 

- [x] Implement function generation one-time address
- [x] Integrate one-time address in creating transaction (normal tx, privacy token tx)
- [x] Store output coins and get list output coins from DB
- [x] Store output coins and get list output coins cross shard from DB
- [x] Update RPCs create and send tx  (normal tx, privacy token tx)
- [x] Store and get tx by public key and viewing key from DB
- [ ] Update gomobile functions
- [ ] Update Web-JS

**Comment by 0xkraken** [comment]
will be done by Nov 22, 2019

**Comment by thaibao-incognito** [comment]
finished: 50%

**Comment by 0xkraken** [comment]
Pending
