### ISSUE TITLE
[privacy] optimize inner product proof 

### ISSUE THREAD

**Issue by 0xkraken** [incognitochain/incognito-chain#415]
relative #307

- [x] Multi-Exponentiation and Batch Verification

**Comment by thaibao-incognito** [comment]
Deadline 22/11/2019

**Comment by hieu013** [comment]
*Optimize Result:*

| Number of Outputs | <1     | <2     | <4     | <8     | <16    |
|-------------------|--------|--------|--------|--------|--------|
| Verify            | 17.16  | 33.27  | 65.06  | 144.18 | 258.96 |
| VerifyFaster      | 10.72  | 19.75  | 37.96  | 74.99  | 147.10 |
| Optimized         | 37.52% | 40.64% | 41.65% | 47.99% | 43.19% |
