### ISSUE TITLE
Wrong processing for multiple simultaneous pdex instructions

### ISSUE THREAD

**Issue by 0xankylosaurus** [incognitochain/incognito-chain#451]
Having wrong processing for multiple simultaneous pdex instructions come from different shard2beacon blocks that will produce new instructions in the same beacon block.

**Comment by thaibao-incognito** [comment]
Complete before 2019-11-15

**Comment by 0xankylosaurus** [comment]
Fixed and passed on testnet env @thaibao-incognito.
