### ISSUE TITLE
[Wallet] Cannot estimate fee in pXYZ for the transaction of sending pXYZ from a wallet to another

### ISSUE THREAD

**Issue by jasonvuongle** [incognitochain/incognito-chain#454]
I created pXYZ token in Incognito wallet. When I sent pXYZ to another Incognito wallet, the wallet could not estimate the transaction fee in pXYZ by showing 'Something went wrong while estimating fee for this transaction. Please try again'. Choosing 'use PRV' for transaction fee, the estimating of the fee back to the normal status.

**Comment by thaibao-incognito** [comment]
When user wants to pay the fee by privacy token, that token needs to be on DEX and has a suitable rate. User can not use any token to pay a fee of incognito tx, it makes a spam tx
