### ISSUE TITLE
[wallet] It takes too long to deposit coins into the wallet

### ISSUE THREAD

**Issue by jasonvuongle** [incognitochain/incognito-chain#456]
I am depositing my ETHs into Incognito wallet. The transaction was successfully executed at 4:03 pm. The deposit order appeared in my wallet about 30 minutes later, 4:36 pm. Now I have been waiting for 30 minutes more but the deposit transaction is still a pending one.

**Comment by thaibao-incognito** [comment]
Because this is a better thing you  need to ask app, @hoangphuongcs make 6 minutes for a cron job to process deposits on decentralize bridge token and all of them ~ 20 - 30 minutes for deposit ETH

**Comment by thaibao-incognito** [comment]
I think it ok because light node of eth have just synced newest data from eth network to confirm the deposit tx
