### ISSUE TITLE
Pending pBTC withdrawal request for 12 hours

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-chain#504]
User @Zavis78 withdraw 0.0294 pBTC but it is not completed for 12 hours
Txid: https://mainnet.incognito.org/tx/72e7959fc1f9a151b27f90f3c712a523ad384fc7d7f20b51b1a76e5851d2d9e6
Address: 12RxTxj3Dqxy2XE1vxivHQfxaNRmrutu3PSTxGX1E4bLySeZMku7mZQJgKfWbRMrYhnGsKH9wiQyRVyUTPPmgVJ3zH4pBYpcTY3jcuj
Address: 34N9PWbzSee3F2c867M21Hir3PZeVP5j9Q
![photo_2019-11-25_17-17-11](https://user-images.githubusercontent.com/57339122/69531993-7a0f4e80-0fa7-11ea-9a13-09cad834da03.jpg)
![photo_2019-11-25_17-17-05](https://user-images.githubusercontent.com/57339122/69532002-809dc600-0fa7-11ea-8757-abe01e8cb268.jpg)
![photo_2019-11-25_17-18-32](https://user-images.githubusercontent.com/57339122/69532067-a2974880-0fa7-11ea-979e-988017ad9788.jpg)

**Comment by thaibao-incognito** [comment]
This is a bug in code, when having 2 cross shard data from  2 shard to one shard -> fetch data about output coin fail -> we need fix issue an clear DB each of nodes committee and resync again to fetch exactly new data

Note: still keep data all blocks, this is not a reset DB issue
