### ISSUE TITLE
Lots of undefined variables when trying to build

### ISSUE THREAD

**Issue by pdsccode** [incognitochain/incognito-chain#532]
When trying to build via `go build -o incognito` I get several errors about undefined variables or methods:

`github.com/libp2p/go-libp2p-peerstore/pstoremem
../../libp2p/go-libp2p-peerstore/pstoremem/addr_book.go:154:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p-peerstore/pstoremem/addr_book.go:197:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
github.com/libp2p/go-mplex
../../libp2p/go-mplex/multiplex.go:202:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:489:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:501:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:539:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/stream.go:206:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
github.com/libp2p/go-libp2p-transport-upgrader
../../libp2p/go-libp2p-transport-upgrader/listener.go:130:9: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
github.com/libp2p/go-libp2p-secio
../../libp2p/go-libp2p-secio/protocol.go:117:11: log.EventBegin undefined (type *log.ZapEventLogger has no field or method EventBegin)
github.com/libp2p/go-libp2p-loggables
../../libp2p/go-libp2p-loggables/loggables.go:19:26: undefined: log.Loggable
../../libp2p/go-libp2p-loggables/loggables.go:20:9: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:27:21: undefined: log.Loggable
../../libp2p/go-libp2p-loggables/loggables.go:28:9: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:33:23: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:38:9: undefined: log.Metadata
github.com/libp2p/go-addr-util
../../libp2p/go-addr-util/addr.go:101:5: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-addr-util/addr.go:101:63: undefined: log.Loggable
../../libp2p/go-addr-util/addr.go:106:10: undefined: log.Metadata
../../libp2p/go-addr-util/addr.go:187:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
github.com/libp2p/go-libp2p/p2p/protocol/identify
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:46:12: undefined: debug.ReadBuildInfo
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:118:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:125:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:188:6: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:197:6: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:197:67: undefined: log.Metadata
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:223:6: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:416:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:23:6: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:38:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:38:6: too many errors
github.com/libp2p/go-libp2p-nat
../../libp2p/go-libp2p-nat/nat.go:186:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
github.com/libp2p/go-reuseport-transport
../../libp2p/go-reuseport-transport/multidialer.go:103:8: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)`

**Comment by thaibao-incognito** [comment]
I think that is only a warning. It still builds to exec file incognito, right?

**Comment by pdsccode** [comment]
Unfortunately not. But I found a workaround by building libp2p first and then trying to build incognito again. After that, the build went through w/o issues.
