### ISSUE TITLE
Detailed design for Portal

### ISSUE THREAD

**Issue by 0xankylosaurus** [incognitochain/incognito-chain#535]
We had a great initial spec for the Portal a few weeks ago at #295, it would be a started point to get an introduction about the Portal project so the issue is to create a detailed design in order for the dev team to be able to implement it inside incognito chain.

**Comment by 0xankylosaurus** [comment]
will be done be the end of Dec 6th, 2019.

**Comment by 0xankylosaurus** [comment]
@thaibao-incognito the deadline of this one will be moving to Dec 9th, 2019 due to adding minimum adding liquidity rule.

**Comment by thaibao-incognito** [comment]
Deadline 30/12/2019
