### ISSUE TITLE
[privacy] Benchmark Optimized Inner Product 

### ISSUE THREAD

**Issue by tnhieu** [incognitochain/incognito-chain#536]
Related Issue #307 

Benchmark the maximum number of privacy transactions in a block.

Deadline: Dec 03, 2019

**Comment by thaibao-incognito** [comment]
Estimated mainnet: 5/12/2019

**Comment by thaibao-incognito** [comment]
Add benchmark?

**Comment by hieu013** [comment]
Benchmark number of privacy tx / 10s

- 1 Input:

| Number of Outputs | 2     | 4     | 8     |
|-------------------  |-----|-----|-----|
| Ver 1  (tx / 10s)                     |  64  | 35  | 17 |
| Ver 2  (tx / 10s)                     | 100  | 55  | 31  |

- 2 inputs

| Number of Outputs | 2     | 4     | 8     |
|-------------------  |-----|-----|-----|
| Ver 1  (tx / 10s)                     |  52  | 32  | 15 |
| Ver 2  (tx / 10s)                     | 80  | 46  | 25|
