### ISSUE TITLE
[Spec] Priority for Random Waiting list of Staker, a new approach

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-chain#565]
Issue: Staker in the waiting list is very a lot and need to random for going into the pending list
-> some staker needs a long time to go in
---> thinking about priority on some weight for random next pending validator

**Comment by 0xbarmanu** [comment]
Random đăng kí shard và chọn vào shard
Từ khoá:
candidate: stake tiền rồi mà chưa được assign 1 shard nào
substitute: đã assign shard rồi mà chưa vào committee
validator: đang ở trong committee
Vấn đề
1. Node mà random qua các shard khác nhau liên tục thì cuối cùng node đó sync data của tất  cả các shard, thành ra mất ý  nghĩa sharding là chia việc ra làm.
2. Nếu cố định 1 address vô 1 shard thì attacker dễ cố tình thử đổi các address cho tới khi chiếm đa số trong  1 shard.
3. Tránh trường hợp starvation, nghĩa là 1 candidate đợi không  hứa hẹn khi nào được vào committee.
Giải pháp
1. Có 8 shards thì tạo 8 FIFO queue
2. Khi 1 node stake thì được random vào 1 queue.
3. Ở mỗi lượt thay committee cho 1 shard: node đầu queue của shard đó được chọn; random 50% số node còn lại trong nữa đầu queue đó, và random ~50%  số node còn lại trong toàn queue đó.
1. Một node làm validator cho 1 shard thì giữ nguyên shard đó cho 4 ngày tiếp theo (sau khi ra khỏi committee, quay  lại hàng đợi thì không cần assign shard mới), nhưng  sau 4 ngày thì buộc random lại để chọn shard. Rule này giúp giảm sync các shard khác nhau.  Và cũng  tránh attacker dồn validator của nó vô 1 shard.
2. Một node đã stake vào làm  candidate  thì nó phải đợi ít  nhất 1 ngày mới rút tiền stake không làm validator nữa. Điều này để chống attacker đưa các validator của mình  vào 1 shard.

Phân tích: 
Có 8 shard, xác suất  random vô 1 shard  là 1/8. Giờ attacker muốn đưa hết  các node của attacker vô 1  shard.  Thì khi stake vô 1 ngày sau mới unstake đc, nghĩa là 1 node của attacker sẽ có 4 lần thử, 4/8 = 1/2 mà nếu muốn chiếm 1/3 committee (giả sử  1/3 committee là 10 nodes) thì xác suất  này  là (1/2)^10 = 1/1024 là khá khó để 1 attacker đưa tất cả node của mình vào chung 1 shard.  Thứ 2 nữa là khi ở trong 1  shard, các node này chưa chắc làm validator cùng 1 lúc vì cơ chế random trên toàn hàng đợi.

**Comment by 0xbarmanu** [comment]
https://docs.google.com/document/d/1Fcd9pB7WrvWEwvWezrIUA2UVIBT6hbfr7WSaPsZSyBY/edit 
Update life cycle of a validator
