### ISSUE TITLE
[consensus] multiple chain view for new consensus

### ISSUE THREAD

**Issue by 0xmerman** [incognitochain/incognito-chain#571]
- [x] spec: document current database storage method (get all type of key, value and how those keys use) (finished 10/12/2019)
- [x] spec: classify key-value types into rawdb or statedb. Define key value for each object/type
- [x] test statedb query by prefix
- [x] implement statedb spec above
- [x] change accessor from rawdb to statedb
==> Deploy local  dbv2 with consensusv1 (15/1/2020)
- [x] test dbv2 in testnet, metric db size
- [x] implement: new database design for blockchainv2 (begin date: 24 Feb 2020)
- [x] test: write unit test for each part (from db to blockchain layer) if possible

**Comment by 0xmerman** [comment]
document v0 main key, value: https://docs.google.com/spreadsheets/d/15PNjw7Rde3pzi7VPUBp7pK7iNKi-wwMfXjnJdMMk8Ws/edit#gid=0

**Comment by 0xmerman** [comment]
update 13/12/2019: implement and test get key by prefix from trie

**Comment by 0xmerman** [comment]
update 14/12/2019: finished test get multiple value by prefix

**Comment by 0xmerman** [comment]
Implement:
- [ ] Committee Object
- [ ] Reward Receiver Object
- [ ] Auto Staking
- [ ] Shard Reward Request
- [ ] Committee Reward 
- [ ] Black List Producer

**Comment by 0xmerman** [comment]
rawdb:
- [ ] latest header
- [ ] latest block 
- [ ] block header
- [ ] block body
- [ ] transaction look up: txHash -> txIndex in block or metadata of tx

**Comment by 0xmerman** [comment]
Additional:
- [ ] StoreTxByPublicKey
- [ ] GetTxByPublicKey

**Comment by 0xmerman** [comment]
Change accessor from rawdb to statedb:
- [ ] beacon consensus
- [ ] shard consensus
- [ ] reward request and withdraw
- [ ] transaction
- [ ] pdex 
- [ ] bridge (burning confirm)

**Comment by 0xmerman** [comment]
Review database partition:
- [ ] beacon
   * [ ] consensus
   * [ ] reward
   * [ ] feature: pdex, bridge, burn 
   * [ ] slash
- [ ] shard 
   * [ ] consensus
   * [ ] transaction
   * [ ] pdex, bridge, burn
   * [ ] reward
   * [ ] slash

**Comment by 0xmerman** [comment]
Test DBV2
- [x] normal transaction dbv2
- [ ] privacy transaction dbv2

**Comment by 0xmerman** [comment]
# implement: new database design for blockchainv2
- [ ] Read and comprehend desgin blockchainv2
- [ ] Add dbv2 to blockchainv2
- [ ] Test

**Comment by khanhlh-incognito** [comment]
related #854
