### ISSUE TITLE
[Mainnet] Docker image for ARM64

### ISSUE THREAD

**Issue by thaibao-incognito** [incognitochain/incognito-chain#573]
![image](https://user-images.githubusercontent.com/24885708/70493369-0427ed00-1b3a-11ea-886c-a74c7a2cc603.png)

**Comment by peterincognito** [comment]
From: @CodedInk
Description:
"The last img you sent is not ARM64.  it needs to be Architecture: aarch64. aarch64 is the latest ARMv8"
![Untitled](https://user-images.githubusercontent.com/57339122/70493978-2b7fb980-1b3c-11ea-880b-0ec4f0859174.png)

**Comment by thaibao-incognito** [comment]
About this issue, we will build a new docker hub repo for arm64 here
https://hub.docker.com/r/incognitochain/incognito-mainnet-arm/tags

**Comment by adrianchifor** [comment]
Hey @thaibao-incognito, is the arm image automatically updated/pushed? Seems to be running 4 months behind
