### ISSUE TITLE
[API] - [pDEX]

### ISSUE THREAD

**Issue by cryptofriend** [incognitochain/incognito-chain#595]
**From:** @Andrey 

**Description:**
We need API to share with the third party next data from pDEX
- [x] List of active trading pairs 

**For each Trading pair** 
- [x] ticker 
- [x] 24h volume
- [x] The timestamp of the last trade
- [x] Trades (X number of trades executed)
--------------
For the leader's board need a one more metric
- [x] top 10 traders wallets for the past 24 hours/7 days/ custom dates (By number of trades, by volume of trades)

----------- UPD Dec 23
- [x] side The direction of the trade [buy, sell]
- [x] raw The raw data of the trade as represented by the exchange. This can be any JSON encodable data.

**Comment by thaibao-incognito** [comment]
Estimated:
Start on 17/12/2019 - End on 19/12/2019

**Comment by thaibao-incognito** [comment]
This is portal to get our data http://34.94.185.164:8080/
