### ISSUE TITLE
The earned PRV is credited to his wallet, but he hasn't received pBTC for 10 hours already.

### ISSUE THREAD

**Issue by 0xmoehau** [incognitochain/incognito-chain#600]
User: @tylerking
In Node detail screen, he withdrew his earning from staking (PRV and pBTC) to his wallet:
12RrzXspWzBJKfWvfeUXaSz9xHPt19mJsk7TECGqMvefL6YQHZ8iKRsy5sRxytVNk4yT4Ee17Jf9uVTxZgpZ8V3rerqgBVQhC6WFkPR
The earned PRV is credited to his wallet, but he hasn't received pBTC for 10 hours already.

**Comment by 0xmoehau** [comment]
https://github.com/incognitochain/incognito-wallet/issues/149

**Comment by thaibao-incognito** [comment]
Withdraw reward tx should be only in a block for 1 public-key -> many withdraw reward tx can not work in the same block
