### ISSUE TITLE
[mainnet] estimate fee is wrong, unable to send PRV and Token

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#616]

**Comment by khanhlh-incognito** [comment]
related https://github.com/incognitochain/incognito-wallet/issues/134

**Comment by tuannguyen100** [comment]
- on RPC : works well in case sent  1shard/Xshard
- on App : sometime raises alert -> not calculating fee -> can't sent

**Comment by tuannguyen100** [comment]
-  PRC on low bandwidth environment (10kbps) works well 

![Screen Shot 2019-12-17 at 11 00 19 AM](https://user-images.githubusercontent.com/58675365/70964625-203e0800-20bf-11ea-84f2-c952ef70e65b.png)

![Screen Shot 2019-12-17 at 11 03 14 AM](https://user-images.githubusercontent.com/58675365/70964626-20d69e80-20bf-11ea-8d57-4ad02f6a7439.png)

**Comment by khanhlh-incognito** [comment]
Not a issue of chain-team.
