### ISSUE TITLE
.git/objects/pack folder is huge

### ISSUE THREAD

**Issue by quantonganh** [incognitochain/incognito-chain#626]
```
1.4G Dec 17 17:20 .git/objects/pack/pack-a66e87e1d99c2f876128332815a43dcd6aea02a0.pack
```

```
❯ git count-objects -v
count: 0
size: 0
in-pack: 76109
packs: 1
size-pack: 1444938
prune-packable: 0
garbage: 0
size-garbage: 0
```

Should we remove this large file reference?

```
166341324338b85b1e68cc56b26ad94cc9b6c9d5 wasm/gomobile/Gomobile.framework/Versions/A/Gomobile
```

https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#_removing_objects

**Comment by thaibao-incognito** [comment]
Can you explain it more detail, please

**Comment by quantonganh** [comment]
Someone accidentally added `Gomobile.framework` in the history. That caused every clone will be forced to download that large folder (even it was removed).
