### ISSUE TITLE
Can not get balance from chain - error code 503

### ISSUE THREAD

**Issue by peterincognito** [incognitochain/incognito-chain#640]
From: @CodedInk @Night1Wolf
Description:
Request failed with status code 503
![photo_2019-12-19_12-09-04](https://user-images.githubusercontent.com/57339122/71146581-6c708000-2258-11ea-91b8-4a514a3ae8b0.jpg)

**Comment by thaibao-incognito** [comment]
We increased max connection to 1500 for every fullnode
