### ISSUE TITLE
[test] New DB

### ISSUE THREAD

**Issue by tuannguyen100** [incognitochain/incognito-chain#760]
Relate #726 #476 

### devnet: round 1
- - [x] transaction: (prv + ptoken)
- - [x] batch verification
- - [x] pdex prv - token
- - [x] pdex token - tooken
- - [x] bridge - centralize
- - [x] bridge - decentralize >> **skip**

### devnet: round 2
- - [x] transaction: (prv + ptoken)
- - [x] batch verification
- - [x] pdex prv - token
- - [x] pdex token - tooken
- - [x] bridge - centralize
- - [ ] bridge - decentralize >> **skip**
- - [x] staking
- - [ ] unstaking
- - [x] withdraw reward prv and token

### testnet
- - [x] transaction: (prv + ptoken)
- - [x] batch verification
- - [ ] pdex prv - token
- - [ ] pdex token - tooken
- - [x] bridge - centralize
- - [ ] bridge - decentralize >> **skip**
- - [ ] staking
- - [ ] withdraw reward prv and token

**Comment by khanhlh-incognito** [comment]
### LOCAL
- [ ] staking
- [ ] reward
- [ ] fault-tolerant 

### TESTNET
- [ ] decentralize bridge 
- [ ] pdex prv, token
- [ ] pdex token, token
