### ISSUE TITLE
[test][auto] implement batchverification automation tests

### ISSUE THREAD

**Issue by thach-incognito** [incognitochain/incognito-chain#770]
- [x] Verify that the chain can produce an at-least-10-tx block
- [x] Invalid transaction will not be processed
- [x] Verify that the chain can produce an at-least-10-tx block - Mixed PRV, pToken, XShard, privacy and no-privacy

**Comment by khanhlh-incognito** [comment]
related to #685

**Comment by khanhlh-incognito** [comment]
https://github.com/incognitochain/incognito-chain-testing/tree/dev/IncognitoChain/TestCases/Performace
