### ISSUE TITLE
[test] pDex and Uniswap integration

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#776]
related to #698 

- [x] Setup environment
- [x] Define Testcase
- [x] Testcase Review with Devs
- [x] Estimation
- [ ] ~Manual test~
- [x] Automation test
- [x] Test report

**Comment by tuannguyen100** [comment]
report 18/03 : 
- Testcase auto 0x and multi trade: 60% (wait dev code multi trade for 0x)
- Testcase auto Kyber & multi trade : 70%
- Testcase auto Migrate Smart Contract : 30%

**Comment by tuannn10** [comment]
report 20/03 :

Testcase auto 0x : 100% (don't apply multit trade with 0x)
Testcase auto Kyber & multi trade : 100%
Testcase auto Migrate Smart Contract : 100%
Test local : 100%
Test on testnet : 70 %

**Comment by tuannguyen100** [comment]
Report 20/03 :

Testcase auto 0x : 100% (don't apply multit trade with 0x)
Testcase auto Kyber & multi trade : 100%
Testcase auto Migrate Smart Contract : 100%
Test local : 100%
Test on testnet : 70 %

**Comment by tuannguyen100** [comment]
Report 27/03 :

- Testcase auto 0x : 100% (don't apply multit trade with 0x)
- Testcase auto Kyber & multi trade : 100%
- Testcase auto Migrate Smart Contract : 100%
- Test local : 100%
- Test on testnet : 100 %
- Support dev
