### ISSUE TITLE
[devnet][bridge] total token amount after withdraw centralize token is not correct

### ISSUE THREAD

**Issue by thach-incognito** [incognitochain/incognito-chain#777]
Environment: dev net, not found in test net
Steps:
    STEP(1, "check user balance before withdrawing token")
    STEP(2, "check the total token amount before withdrawing")
    STEP(3, f"withdraw {withdraw_amount} token")
    STEP(4, "check user balance after withdrawing token")
    STEP(5, "check total token amount in getallbridgetokens")
Expect: total_token_amount_after_withdraw + withdraw_amount == total_token_amount_before
Actual result: total_token_amount_after_withdraw + withdraw_amount != total_token_amount_befor

Test Script: https://github.com/incognitochain/incognito-chain-testing/blob/dev/IncognitoChain/TestCases/Bridge/BRD01_centralize_token.py

Relate #760

**Comment by 0xmerman** [comment]
@thach-incognito i made some fix already, please test this problem again

**Comment by 0xmerman** [comment]
plz close this issue if bug was fix @thach-incognito

**Comment by khanhlh-incognito** [comment]
fixed
