### ISSUE TITLE
[test][hotfix] getbridgereqwithstatus

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#837]

**Comment by tuannguyen100** [comment]
done test
{
    "id": 1,
    "jsonrpc": "1.0",
    "method": "getbridgereqwithstatus",
    "params": [
        {
        	"TxReqID": "ef00f6b1db841b0e961878effa840868b18e424e33b39a5863b809b1bb9497a9"
        }
    ]
}
