### ISSUE TITLE
[test][hotfix] improve get list token response time

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#838]
```
listPrivacyCustomToken:                     (*HttpServer).handleListPrivacyCustomToken,
listPrivacyCustomTokenByShard:              (*HttpServer).handleListPrivacyCustomTokenByShard,
privacyCustomTokenTxs:                      (*HttpServer).handlePrivacyCustomTokenDetail,
getListPrivacyCustomTokenBalance:           (*HttpServer).handleGetListPrivacyCustomTokenBalance,
getBalancePrivacyCustomToken:               (*HttpServer).handleGetBalancePrivacyCustomToken,
```

**Comment by thach-incognito** [comment]
test script: https://github.com/incognitochain/incognito-chain-testing/blob/dev/IncognitoChain/TestCases/Performace/test_PER003_rpc_improve_response_time.py

test result run locally on testnet's fullnode:

>         list_privacy_custom_token :
>             res time  : 1.36744 s
>             size      : 192.1533203125 kb
>             size/time : 140.52047644686422 kb/s
>         list_privacy_custom_token_by_shard :
>             res time  : 1.010704 s
>             size      : 155.734375 kb
>             size/time : 154.08504863936423 kb/s
>         get_list_privacy_custom_token_balance :
>             res time  : 2.046176 s
>             size      : 17.69140625 kb
>             size/time : 8.646082375123157 kb/s
>         get_balance_privacy_custom_token :
>             res time  : 0.078527 s
>             size      : 0.314453125 kb
>             size/time : 4.004394985164338 kb/s
>         privacy_custom_token :
>             res time  : 0.217592 s
>             size      : 108.5439453125 kb
>             size/time : 498.84161785589544 kb/s
