### ISSUE TITLE
[Scalability] Source code review & optimization 

### ISSUE THREAD

**Issue by 0xkumi** [incognitochain/incognito-chain#849]
In order to enhance our network, we will do some review and research to optimize our chain logic.
 - [x] Review schema to prevent race conditions in DBv2.
 - [x] Implement metric feature and RPC for real-time monitor.
 - [ ] Review if we need to partition database into chains so that chains are stored and backup separately

**Comment by 0xmerman** [comment]
metrics: pull request #857
