### ISSUE TITLE
[test][local] consensus v2

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#854]
- [x] transaction 
- [x] stake
- [x] bridge
- [x] pdex
- [x] fault tolerance

**Comment by khanhlh-incognito** [comment]
Report Transaction:
http://68.183.187.162:8888/job/test_suites/job/test_transaction_prv_and_token/4/HTML_20Report/

**Comment by tuannguyen100** [comment]
related #856

**Comment by thach-incognito** [comment]
Reports:
- [Transaction](http://68.183.187.162:8888/job/test_suites/job/test_transaction_prv_and_token/4/HTML_20Report/) 
- [Bridge](http://68.183.187.162:8888/job/test_suites/job/test_bridge/1/HTML_20Report/)
- [Batch verification](http://68.183.187.162:8888/job/test_suites/job/test_batch_verification/2/HTML_20Report/)
- [Staking](http://68.183.187.162:8888/job/test_suites/job/test_staking/1/HTML_20Report/)

**Comment by khanhlh-incognito** [comment]
report pdex 
[pdex_prv_report.log](https://github.com/incognitochain/incognito-chain/files/4484734/pdex_prv_report.log)
[pdex_token_report.log](https://github.com/incognitochain/incognito-chain/files/4484735/pdex_token_report.log)

**Comment by khanhlh-incognito** [comment]
related #861

**Comment by khanhlh-incognito** [comment]
related #864

**Comment by khanhlh-incognito** [comment]
Decentralize Bridge will be tested on testnet
